- name: Run Maven Unit Tests
  run: mvn clean test

- name: Build Docker Image
  run: |
    docker build \
      -t $REGISTRY/${{ github.repository }}:$SHA_TAG \
      -t $REGISTRY/${{ github.repository }}:latest .

- name: Login to Container Registry
  uses: docker/login-action@v3
  with:
    registry: ${{ env.REGISTRY }}
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Push Docker Images
  run: |
    docker push $REGISTRY/${{ github.repository }}:$SHA_TAG
    docker push $REGISTRY/${{ github.repository }}:latest